name: Upload latest data to github release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: t1
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD"
    - name: Save current date
      id: date
      run: echo "date=${{ steps.t1.outputs.time }}" >> $GITHUB_OUTPUT
    - uses: addnab/docker-run-action@v3
      with:
        registry: docker.io
        image: effyroth/em_data:latest
        options: -v /mnt/c/github_runner/effyroth/em_data/:/output -v dolt:/dolt
        run: |
          python my_ak.py
          
    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        # 若无变更则跳过提交
        git diff --cached --quiet || git commit -m "ci: 自动更新 by GitHub Actions"
        git push origin HEAD:${{ github.ref_name }}
      
